function configure_octave_mex(vc_install_dir, ms_sdk)
%CONFIGURE_OCTAVE_MEX function to add compile environment variables in Octave
%

putenv ('path', [vc_install_dir, '\bin;', ...
                 ms_sdk, '\bin;', ...
                 vc_install_dir, '\include;', ...
                 ms_sdk, '\lib;', ...
                 vc_install_dir, '\..\Common7\IDE;', ...
                 getenv('path')]);
                 
putenv ('include', [vc_install_dir, '\include;', ...
                    ms_sdk, '\include;', ...
                    getenv('include')]);

putenv ('lib', [vc_install_dir, '\lib;', ...
                ms_sdk, '\lib;', ...
                getenv('lib')]);

